theme: jekyll-theme-cayman

title: Radiology Reports-driven Diffusion for CT Image Synthesis and Semantic Manipulation
description: A novel radiology Reports-driven diffusion method can generate high-quality synthetic data for downstream diagnostic tasks. <br /> (Preprinting.)
